In [1]:
#importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel("Bank_Personal_Loan_Modelling.xlsx",na_values=['.',':','?','!','@','#','$','%','^','&','*',','])

In [3]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ID                  5000 non-null   int64  
 1   Age                 5000 non-null   int64  
 2   Experience          5000 non-null   int64  
 3   Income              5000 non-null   int64  
 4   ZIP Code            5000 non-null   int64  
 5   Family              5000 non-null   int64  
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64  
 8   Mortgage            5000 non-null   int64  
 9   Personal Loan       5000 non-null   int64  
 10  Securities Account  5000 non-null   int64  
 11  CD Account          5000 non-null   int64  
 12  Online              5000 non-null   int64  
 13  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [5]:
df.nunique()

ID                    5000
Age                     45
Experience              47
Income                 162
ZIP Code               467
Family                   4
CCAvg                  108
Education                3
Mortgage               347
Personal Loan            2
Securities Account       2
CD Account               2
Online                   2
CreditCard               2
dtype: int64

In [6]:
df = df.drop(["ID","ZIP Code",], axis=1)

In [7]:
df.isnull().sum()

Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [8]:
df.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

In [9]:
df.dtypes

Age                     int64
Experience              int64
Income                  int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Personal Loan           int64
Securities Account      int64
CD Account              int64
Online                  int64
CreditCard              int64
dtype: object

In [10]:
for col in ['Education','Securities Account','CD Account','Online','Personal Loan','Family','CreditCard']:
  df[col] = df[col].astype('category')

In [11]:
df.dtypes

Age                      int64
Experience               int64
Income                   int64
Family                category
CCAvg                  float64
Education             category
Mortgage                 int64
Personal Loan         category
Securities Account    category
CD Account            category
Online                category
CreditCard            category
dtype: object

In [12]:
cat_cols=['Family','Education','CreditCard','Securities Account','CD Account','Online']

In [13]:
num_cols=['Age','Income', 'Experience', 'CCAvg', 'Mortgage']

In [14]:
df[num_cols].describe()

Age       Income   Experience        CCAvg     Mortgage
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000
mean     45.338400    73.774200    20.104600     1.937938    56.498800
std      11.463166    46.033729    11.467954     1.747659   101.713802
min      23.000000     8.000000    -3.000000     0.000000     0.000000
25%      35.000000    39.000000    10.000000     0.700000     0.000000
50%      45.000000    64.000000    20.000000     1.500000     0.000000
75%      55.000000    98.000000    30.000000     2.500000   101.000000
max      67.000000   224.000000    43.000000    10.000000   635.000000

In [15]:
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [16]:
X = df.drop('Personal Loan',axis=1)
y= df['Personal Loan']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=125, stratify=y)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4000, 11)
(1000, 11)
(4000,)
(1000,)


In [19]:
df.value_counts(['Personal Loan'])/5000

Personal Loan
0                0.904
1                0.096
dtype: float64

In [20]:
y_train.value_counts(normalize=True)

0    0.904
1    0.096
Name: Personal Loan, dtype: float64

In [21]:
y_test.value_counts(normalize=True)

0    0.904
1    0.096
Name: Personal Loan, dtype: float64

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler = scaler.fit(X_train[num_cols])
X_train_num_std = pd.DataFrame(scaler.transform(X_train[num_cols]), columns=X_train[num_cols].columns)
X_test_num_std = pd.DataFrame(scaler.transform(X_test[num_cols]), columns=X_test[num_cols].columns)

In [23]:
X_train_num_std.isnull().sum()

Age           0
Income        0
Experience    0
CCAvg         0
Mortgage      0
dtype: int64

In [24]:
X_test_num_std.isnull().sum()

Age           0
Income        0
Experience    0
CCAvg         0
Mortgage      0
dtype: int64

In [25]:
X_train_num_std = X_train_num_std.reset_index()
X_train_num_std

index       Age    Income  Experience     CCAvg  Mortgage
0         0 -0.395890 -1.096353   -0.374914 -0.304167 -0.557909
1         1  0.738466  0.115894    0.758546 -0.189991 -0.557909
2         2  0.563950 -0.879880    0.584168 -0.703782 -0.557909
3         3  0.738466 -0.273757    0.845736 -0.075816 -0.557909
4         4 -0.221374 -0.511877   -0.200535 -0.018728 -0.557909
...     ...       ...       ...         ...       ...       ...
3995   3995 -0.657665  1.393083   -0.723671 -1.103397 -0.557909
3996   3996  0.476692  2.302269    0.409789 -0.132903 -0.557909
3997   3997 -1.355731 -0.706702   -1.333995 -0.132903 -0.557909
3998   3998 -0.308632 -1.291179   -0.287724 -1.046309 -0.557909
3999   3999 -1.355731  0.137541   -1.246806 -0.247079  1.585251

[4000 rows x 6 columns]

In [26]:
X_train_num_std = X_train_num_std.drop(["index"], axis=1)

In [27]:
X_train_num_std

Age    Income  Experience     CCAvg  Mortgage
0    -0.395890 -1.096353   -0.374914 -0.304167 -0.557909
1     0.738466  0.115894    0.758546 -0.189991 -0.557909
2     0.563950 -0.879880    0.584168 -0.703782 -0.557909
3     0.738466 -0.273757    0.845736 -0.075816 -0.557909
4    -0.221374 -0.511877   -0.200535 -0.018728 -0.557909
...        ...       ...         ...       ...       ...
3995 -0.657665  1.393083   -0.723671 -1.103397 -0.557909
3996  0.476692  2.302269    0.409789 -0.132903 -0.557909
3997 -1.355731 -0.706702   -1.333995 -0.132903 -0.557909
3998 -0.308632 -1.291179   -0.287724 -1.046309 -0.557909
3999 -1.355731  0.137541   -1.246806 -0.247079  1.585251

[4000 rows x 5 columns]

In [28]:
X_test_num_std = X_test_num_std.reset_index()
X_test_num_std

index       Age    Income  Experience     CCAvg  Mortgage
0        0 -0.395890 -0.901528   -0.549292 -0.532518 -0.557909
1        1 -1.617505 -0.728350   -1.508374 -1.046309  0.528350
2        2  0.040401  1.717792    0.148222  3.178193 -0.557909
3        3  1.436532  2.064149    1.456060  1.750996  1.242737
4        4 -1.181214 -0.641760   -1.072427 -0.075816  1.321026
..     ...       ...       ...         ...       ...       ...
995    995  0.302175 -1.334473    0.235411 -1.046309 -0.557909
996    996 -0.570407  1.198258   -0.462103 -0.018728 -0.557909
997    997  1.087499 -0.013990    1.020114 -0.703782 -0.557909
998    998 -1.355731 -0.208815   -1.246806  0.837590  0.587067
999    999 -0.395890  0.981785   -0.287724  2.378963  2.015840

[1000 rows x 6 columns]

In [29]:
X_test_num_std = X_test_num_std.drop(["index"], axis=1)

In [30]:
X_test_num_std

Age    Income  Experience     CCAvg  Mortgage
0   -0.395890 -0.901528   -0.549292 -0.532518 -0.557909
1   -1.617505 -0.728350   -1.508374 -1.046309  0.528350
2    0.040401  1.717792    0.148222  3.178193 -0.557909
3    1.436532  2.064149    1.456060  1.750996  1.242737
4   -1.181214 -0.641760   -1.072427 -0.075816  1.321026
..        ...       ...         ...       ...       ...
995  0.302175 -1.334473    0.235411 -1.046309 -0.557909
996 -0.570407  1.198258   -0.462103 -0.018728 -0.557909
997  1.087499 -0.013990    1.020114 -0.703782 -0.557909
998 -1.355731 -0.208815   -1.246806  0.837590  0.587067
999 -0.395890  0.981785   -0.287724  2.378963  2.015840

[1000 rows x 5 columns]

In [31]:
X_train_cat = X_train[cat_cols].reset_index()
X_train_cat

index Family Education CreditCard Securities Account CD Account Online
0       851      2         2          0                  1          0      1
1      3744      3         3          0                  0          0      0
2      1394      2         2          1                  0          0      0
3      1997      1         3          0                  0          0      1
4      1507      4         3          0                  0          0      0
...     ...    ...       ...        ...                ...        ...    ...
3995   1005      2         1          0                  1          0      1
3996   3168      1         1          0                  0          0      1
3997    386      4         2          0                  0          0      1
3998   2293      2         2          0                  0          0      1
3999   1296      3         1          0                  0          0      1

[4000 rows x 7 columns]

In [32]:
X_train_cat = X_train_cat.drop(["index"], axis=1)

In [33]:
X_train_cat

Family Education CreditCard Securities Account CD Account Online
0         2         2          0                  1          0      1
1         3         3          0                  0          0      0
2         2         2          1                  0          0      0
3         1         3          0                  0          0      1
4         4         3          0                  0          0      0
...     ...       ...        ...                ...        ...    ...
3995      2         1          0                  1          0      1
3996      1         1          0                  0          0      1
3997      4         2          0                  0          0      1
3998      2         2          0                  0          0      1
3999      3         1          0                  0          0      1

[4000 rows x 6 columns]

In [34]:
X_test_cat = X_test[cat_cols].reset_index()
X_test_cat

index Family Education CreditCard Securities Account CD Account Online
0     3647      3         2          1                  0          0      0
1     1093      3         2          0                  0          0      1
2     4911      2         1          0                  0          0      0
3     3006      3         2          1                  0          1      1
4     3495      1         2          0                  0          0      1
..     ...    ...       ...        ...                ...        ...    ...
995   1151      2         3          0                  1          1      1
996   2294      2         1          0                  0          0      0
997    122      2         2          1                  0          0      1
998   1283      4         1          0                  0          0      0
999   3029      2         1          0                  1          0      1

[1000 rows x 7 columns]

In [35]:
X_test_cat = X_test_cat.drop(["index"], axis=1)

In [36]:
X_test_cat

Family Education CreditCard Securities Account CD Account Online
0        3         2          1                  0          0      0
1        3         2          0                  0          0      1
2        2         1          0                  0          0      0
3        3         2          1                  0          1      1
4        1         2          0                  0          0      1
..     ...       ...        ...                ...        ...    ...
995      2         3          0                  1          1      1
996      2         1          0                  0          0      0
997      2         2          1                  0          0      1
998      4         1          0                  0          0      0
999      2         1          0                  1          0      1

[1000 rows x 6 columns]

In [37]:
final_X_train = pd.concat([X_train_num_std, X_train_cat], axis=1)

In [38]:
final_X_test = pd.concat([X_test_num_std, X_test_cat], axis=1)

In [39]:
final_X_train.isnull().sum()

Age                   0
Income                0
Experience            0
CCAvg                 0
Mortgage              0
Family                0
Education             0
CreditCard            0
Securities Account    0
CD Account            0
Online                0
dtype: int64

In [40]:
final_X_test.isnull().sum()

Age                   0
Income                0
Experience            0
CCAvg                 0
Mortgage              0
Family                0
Education             0
CreditCard            0
Securities Account    0
CD Account            0
Online                0
dtype: int64

In [41]:
final_X_train

Age    Income  Experience     CCAvg  Mortgage Family Education  \
0    -0.395890 -1.096353   -0.374914 -0.304167 -0.557909      2         2   
1     0.738466  0.115894    0.758546 -0.189991 -0.557909      3         3   
2     0.563950 -0.879880    0.584168 -0.703782 -0.557909      2         2   
3     0.738466 -0.273757    0.845736 -0.075816 -0.557909      1         3   
4    -0.221374 -0.511877   -0.200535 -0.018728 -0.557909      4         3   
...        ...       ...         ...       ...       ...    ...       ...   
3995 -0.657665  1.393083   -0.723671 -1.103397 -0.557909      2         1   
3996  0.476692  2.302269    0.409789 -0.132903 -0.557909      1         1   
3997 -1.355731 -0.706702   -1.333995 -0.132903 -0.557909      4         2   
3998 -0.308632 -1.291179   -0.287724 -1.046309 -0.557909      2         2   
3999 -1.355731  0.137541   -1.246806 -0.247079  1.585251      3         1   

     CreditCard Securities Account CD Account Online  
0             0                  1          0      1  
1             0                  0          0      0  
2             1                  0          0      0  
3             0                  0          0      1  
4             0                  0          0      0  
...         ...                ...        ...    ...  
3995          0                  1          0      1  
3996          0                  0          0      1  
3997          0                  0          0      1  
3998          0                  0          0      1  
3999          0                  0          0      1  

[4000 rows x 11 columns]

In [42]:
final_X_test

Age    Income  Experience     CCAvg  Mortgage Family Education  \
0   -0.395890 -0.901528   -0.549292 -0.532518 -0.557909      3         2   
1   -1.617505 -0.728350   -1.508374 -1.046309  0.528350      3         2   
2    0.040401  1.717792    0.148222  3.178193 -0.557909      2         1   
3    1.436532  2.064149    1.456060  1.750996  1.242737      3         2   
4   -1.181214 -0.641760   -1.072427 -0.075816  1.321026      1         2   
..        ...       ...         ...       ...       ...    ...       ...   
995  0.302175 -1.334473    0.235411 -1.046309 -0.557909      2         3   
996 -0.570407  1.198258   -0.462103 -0.018728 -0.557909      2         1   
997  1.087499 -0.013990    1.020114 -0.703782 -0.557909      2         2   
998 -1.355731 -0.208815   -1.246806  0.837590  0.587067      4         1   
999 -0.395890  0.981785   -0.287724  2.378963  2.015840      2         1   

    CreditCard Securities Account CD Account Online  
0            1                  0          0      0  
1            0                  0          0      1  
2            0                  0          0      0  
3            1                  0          1      1  
4            0                  0          0      1  
..         ...                ...        ...    ...  
995          0                  1          1      1  
996          0                  0          0      0  
997          1                  0          0      1  
998          0                  0          0      0  
999          0                  1          0      1  

[1000 rows x 11 columns]

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
lr = LogisticRegression()
lr = lr.fit(final_X_train,y_train)

In [45]:
y_train_preds = lr.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [46]:
y_test_preds = lr.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [47]:
from sklearn.metrics import confusion_matrix
confusionmatrix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[3569,   47],
       [ 147,  237]])

In [48]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[892,  12],
       [ 36,  60]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

0.9515

In [50]:
accuracy_score(y_test,y_test_preds)

0.952

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rfc = RandomForestClassifier()
rfc = rfc.fit(final_X_train, y_train)

In [53]:
y_train_preds = rfc.predict(final_X_train)
y_train_preds[0:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [54]:
y_test_preds = rfc.predict(final_X_test)
y_test_preds[0:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [55]:
from sklearn.metrics import confusion_matrix
confusionma2trix = confusion_matrix(y_train,y_train_preds)
confusionmatrix

array([[892,  12],
       [ 36,  60]])

In [56]:
confusionmatrix = confusion_matrix(y_test,y_test_preds)
confusionmatrix

array([[903,   1],
       [ 12,  84]])

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_preds)

1.0

In [58]:
accuracy_score(y_test,y_test_preds)

0.987

In [60]:
import pickle


In [61]:
print('saving model as pkl file.......')
pickle.dump(rfc, open('lr.pkl','wb'))

saving model as pkl file.......
